[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_swap_dapp = "J1KNgjD2T5M1wzi9fqJhBCmcLV8yp1r86AnarpZvySST"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/kien6034/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
